all: 
	gcc -o tlsserver tlsserver.c -lssl -lcrypto
	gcc -o tlsserver5 tlsserver5.c -lssl -lcrypto -lcrypt
	gcc -o tlsserver6 tlsserver6.c -lssl -lcrypto -lcrypt

clean: 
	rm tlsserver tlsserver5 tlsserver6
